version: "3.8"

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: ielts-n8n
    restart: unless-stopped
    ports:
      - "5800:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - GENERIC_TIMEZONE=Asia/Taipei
      - DISCORD_WEBHOOK_URL=https://discord.com/api/webhooks/1490915452631650306/ccglLeI-LK_Ki_KJ0DpUBwAWf-HA7O84AzhylNAogC6nY80F3oh0tyFAJuy1GTXbSSnp
    volumes:
      - n8n_data:/home/node/.n8n
      - ./apps/web/n8n:/home/node/workflows:ro

volumes:
  n8n_data:
